server:
  port: 8706
  servlet:
    context-path: /hdms
spring:
  #数据源
  datasource:
    url: jdbc:mysql://101.37.16.60:3308/hdms?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis
  redis:
    host: 101.37.16.60
    port: 6379
    password: 123456
  activiti:
    database-schema-update: true
    db-history-used: true
  #邮件配置
  mail:
    host: smtp.163.com
    port: 25
    protocol: smtp
    username: hdmsserver@163.com
    password: XBXBEETDWDDBJGWS
    default-encoding: UTF-8
  thymeleaf:
    cache: false
mybatis-plus:
  mapper-locations: classpath*:com/hkb/hdms/mapper/xml/*.xml
  type-aliases-package: com.hkb.hdms.model.pojo